from __future__ import annotations

COMPOSITION_PROFILES: dict[str, dict] = {
    "cinematic_minimal": {
        "label": "Cinematic Minimal",
        "framing": "wide negative space, subject in lower third, clean top band for overlay",
        "typography_scale": {"brand": 32, "title": 21, "tag": 17},
        "logo_placement": "top_left_compact",
        "lighting_mood": "soft rim light, deep charcoal shadows, restrained gold highlights",
        "overlay_style": "thin top gradient band, minimal border",
        "visual_balance": "asymmetric left anchor, airy right headline block",
        "shade_top_alpha": 108,
        "shade_body_alpha": 0,
        "border_radius": 26,
        "outline_alpha": 140,
        "title_offset_y": 4,
        "tag_offset_y": 38,
    },
    "luxury_finance": {
        "label": "Luxury Finance",
        "framing": "center-weighted executive portrait, balanced vertical symmetry",
        "typography_scale": {"brand": 36, "title": 24, "tag": 19},
        "logo_placement": "top_left_prominent",
        "lighting_mood": "rich gold key light, premium private banking atmosphere",
        "overlay_style": "full safe-zone frame with gold outline",
        "visual_balance": "centered prestige layout, equal visual weight",
        "shade_top_alpha": 126,
        "shade_body_alpha": 18,
        "border_radius": 32,
        "outline_alpha": 156,
        "title_offset_y": 6,
        "tag_offset_y": 42,
    },
    "gulf_business_lifestyle": {
        "label": "Gulf Business Lifestyle",
        "framing": "environmental business scene, subject off-center right",
        "typography_scale": {"brand": 34, "title": 22, "tag": 18},
        "logo_placement": "top_left_with_rule",
        "lighting_mood": "warm Gulf golden hour, glass architecture reflections",
        "overlay_style": "top band plus subtle side vignette",
        "visual_balance": "right-aligned headline stack, logo anchors left",
        "shade_top_alpha": 118,
        "shade_body_alpha": 12,
        "border_radius": 30,
        "outline_alpha": 148,
        "title_offset_y": 5,
        "tag_offset_y": 40,
    },
    "modern_exchange_office": {
        "label": "Modern Exchange Office",
        "framing": "interior exchange counter, subject mid-frame, professional depth",
        "typography_scale": {"brand": 35, "title": 23, "tag": 18},
        "logo_placement": "top_left_structured",
        "lighting_mood": "cool-neutral office light with gold accent trim",
        "overlay_style": "structured rectangular frame, crisp divider line",
        "visual_balance": "grid-aligned typography, corporate clarity",
        "shade_top_alpha": 122,
        "shade_body_alpha": 14,
        "border_radius": 28,
        "outline_alpha": 152,
        "title_offset_y": 6,
        "tag_offset_y": 41,
    },
    "premium_travel_finance": {
        "label": "Premium Travel Finance",
        "framing": "travel mobility scene, subject upper-center, motion-friendly crop",
        "typography_scale": {"brand": 33, "title": 22, "tag": 17},
        "logo_placement": "top_left_light",
        "lighting_mood": "cinematic travel lighting, lounge and airport elegance",
        "overlay_style": "soft top fade, minimal lower breathing room",
        "visual_balance": "elevated headline, lighter footer presence",
        "shade_top_alpha": 112,
        "shade_body_alpha": 8,
        "border_radius": 30,
        "outline_alpha": 142,
        "title_offset_y": 4,
        "tag_offset_y": 39,
    },
}

PROFILE_IDS = list(COMPOSITION_PROFILES.keys())
