from __future__ import annotations

THEMES = [
    {
        "id": "oman_luxury_finance",
        "title": "خدمات مالی لوکس در عمان",
        "subtitle": "OMAN PRIVATE EXCHANGE",
        "body": "برای انتقال ارز، دریافت نقدی و پرداخت بین‌المللی با استاندارد حرفه‌ای.",
        "country": "Oman",
        "tags": ["#صرافی_عمان", "#حواله_ارزی", "#Omoney"],
    },
    {
        "id": "turkey_exchange_market",
        "title": "انتقال پول بین عمان و ترکیه",
        "subtitle": "TURKEY EXCHANGE MARKET",
        "body": "راهکاری سریع و مطمئن برای تجارت، سفر و پرداخت‌های بین‌المللی.",
        "country": "Turkey",
        "tags": ["#ترکیه", "#انتقال_پول", "#نرخ_ارز"],
    },
    {
        "id": "egypt_remittance",
        "title": "حواله امن به مصر",
        "subtitle": "EGYPT REMITTANCE",
        "body": "پرداخت و دریافت بین‌المللی با پیگیری دقیق و تجربه‌ای حرفه‌ای.",
        "country": "Egypt",
        "tags": ["#مصر", "#حواله", "#خدمات_مالی"],
    },
    {
        "id": "gcc_money_transfer",
        "title": "انتقال امن ارز در منطقه GCC",
        "subtitle": "GCC MONEY TRANSFER",
        "body": "خدمات ارزی بین عمان، امارات، ترکیه و مسیرهای تجاری بین‌المللی.",
        "country": "GCC",
        "tags": ["#GCC", "#امارات", "#صرافی"],
    },
    {
        "id": "international_bank_transfer",
        "title": "پرداخت و دریافت بین‌المللی",
        "subtitle": "GLOBAL BANK TRANSFER",
        "body": "برای کسب‌وکارها، خانواده‌ها و سرمایه‌گذاران با نیازهای ارزی جدی.",
        "country": "Global",
        "tags": ["#بانکداری", "#پرداخت_بین_المللی", "#Omoney"],
    },
    {
        "id": "currency_exchange",
        "title": "صرافی مدرن برای تجارت جهانی",
        "subtitle": "CURRENCY EXCHANGE",
        "body": "تبدیل ارز، حواله و مشاوره مالی با نگاه دقیق به بازار.",
        "country": "Market",
        "tags": ["#تبدیل_ارز", "#دلار", "#بازار_ارز"],
    },
    {
        "id": "cash_pickup",
        "title": "دریافت نقدی سریع و مطمئن",
        "subtitle": "CASH PICKUP",
        "body": "راهکاری ساده برای دریافت وجه در مسیرهای معتبر و قابل پیگیری.",
        "country": "Service",
        "tags": ["#دریافت_نقدی", "#حواله_ارزی", "#صرافی"],
    },
    {
        "id": "investment_lifestyle",
        "title": "مالی، سرمایه‌گذاری و سبک زندگی بین‌المللی",
        "subtitle": "INVESTMENT LIFESTYLE",
        "body": "برای تصمیم‌های مالی بزرگ، انتقال ارز باید حرفه‌ای و قابل اعتماد باشد.",
        "country": "Lifestyle",
        "tags": ["#سرمایه_گذاری", "#سبک_زندگی", "#مالی"],
    },
    {
        "id": "dubai_financial_district",
        "title": "از عمان تا دبی، مسیر مالی حرفه‌ای",
        "subtitle": "DUBAI FINANCIAL DISTRICT",
        "body": "خدمات ارزی برای تجارت منطقه‌ای، سفرهای کاری و انتقال سرمایه.",
        "country": "Dubai",
        "tags": ["#دبی", "#امارات", "#مالی"],
    },
    {
        "id": "gold_forex_visual",
        "title": "طلا و ارز، با نگاه دقیق بازار",
        "subtitle": "GOLD & FOREX",
        "body": "برای کسانی که نرخ، زمان و اعتبار در انتقال ارز برایشان مهم است.",
        "country": "Forex",
        "tags": ["#طلا", "#فارکس", "#نرخ_ارز"],
    },
    {
        "id": "premium_business_travel",
        "title": "انتقال پول برای سفر و تجارت",
        "subtitle": "BUSINESS TRAVEL FINANCE",
        "body": "از فرودگاه تا دفتر کار، خدمات مالی بین‌المللی باید روان و مطمئن باشد.",
        "country": "Travel",
        "tags": ["#سفر", "#تجارت", "#حواله"],
    },
    {
        "id": "airport_transfer",
        "title": "حواله ارزی در مسیرهای بین‌المللی",
        "subtitle": "AIRPORT TRANSFER ATMOSPHERE",
        "body": "برای خانواده، تجارت و پرداخت‌های فوری در مسیرهای خارجی.",
        "country": "Airport",
        "tags": ["#فرودگاه", "#انتقال_پول", "#Omoney"],
    },
]

VISUAL_PRESETS = [
    {"id": "gold_market_style", "label": "Gold Market Style", "motif": "coins", "primary": "#E8C56F", "secondary": "#5A4016"},
    {"id": "dubai_skyline", "label": "Dubai Skyline", "motif": "skyline", "primary": "#D7B56A", "secondary": "#253B57"},
    {"id": "oman_luxury_office", "label": "Oman Luxury Office", "motif": "arches", "primary": "#E5BF78", "secondary": "#3A2E22"},
    {"id": "forex_dashboard", "label": "Forex Dashboard", "motif": "chart", "primary": "#F1D58F", "secondary": "#18362F"},
    {"id": "airport_transfer", "label": "Airport Transfer", "motif": "routes", "primary": "#E9C676", "secondary": "#2B3444"},
    {"id": "businessman_silhouette", "label": "Businessman Silhouette", "motif": "silhouette", "primary": "#E0B866", "secondary": "#202020"},
    {"id": "banking_transfer", "label": "Banking Transfer", "motif": "columns", "primary": "#F0D18A", "secondary": "#263027"},
    {"id": "fintech_style", "label": "Fintech Style", "motif": "network", "primary": "#EBCB82", "secondary": "#102A34"},
    {"id": "black_marble_luxury", "label": "Black Marble Luxury", "motif": "marble", "primary": "#F4D998", "secondary": "#1A1714"},
    {"id": "dark_trading_desk", "label": "Dark Trading Desk", "motif": "candles", "primary": "#DAB15B", "secondary": "#111B24"},
    {"id": "luxury_currency_exchange", "label": "Luxury Currency Exchange", "motif": "currency", "primary": "#F2D28A", "secondary": "#332618"},
    {"id": "international_remittance", "label": "International Remittance", "motif": "globe", "primary": "#E7C16F", "secondary": "#1C2F3D"},
]

HEADLINES = [
    "انتقال امن ارز بین‌المللی",
    "خدمات حرفه‌ای حواله ارزی",
    "پرداخت و دریافت بین‌المللی",
    "صرافی مدرن برای تجارت جهانی",
    "انتقال پول بین عمان، ترکیه و امارات",
    "دریافت نقدی سریع و قابل پیگیری",
    "خدمات ارزی برای تجارت و سفر",
    "تجربه‌ای لوکس در انتقال ارز",
]
